import 0.9.9
2002-07-30  James Antill  <james@and.org>

	* NEWS: Release 0.9.9

	* tst/add_fmt/tst_double.c (tst): Remove ' flag from formats that
	can't use it.

	* tst/add_fmt/tst_long_double.c (tst): Remove ' flag from formats that
	can't use it.

	* README: Add text about inline helper functions.

	* include/vstr-extern.h.pre: Always include helper functions are you
	can't compile without inline support.

2002-07-29  James Antill  <james@and.org>

	* scripts/autocheck.sh (conf): Change valgrind to only output stuff on
	error (and then into the err log).

	* README: Document how to add functions.

	* configure.in (AC_ARG_ENABLE(tst-noline)): Added option for testing.
	(AC_ARG_ENABLE(tst-noattr-alias)): Added option for testing.
	(AC_ARG_ENABLE(tst-noattr-visibility)): Added option for testing.

	* src/vstr_export.c (vstr_export_buf): Added a size limiter for the
	data ... probably not needed most of the time, but it's better than
	having people get it wrong.
	(vstr_export_iovec_cpy_buf): Fixed return value to be correct.
	(vstr_nx_export_iovec_cpy_buf): Fixed major bug of using the wrong
	int causing an infinite loop.

2002-07-26  James Antill  <james@and.org>

	* Documentation/constants.txt (Constant): Added documentation for
	VSTR_COMPILE_ constants.

2002-07-23  James Antill  <james@and.org>

	* src/vstr_sc_posix.c (vstr__sc_read_slow_fd): Added code so that
	vstr_sc_read_fd() won't just fail if a cache isn't available on the
	Vstr.

	* src/vstr_conv.c (vstr_conv_encode_uri): Remove sprintf() call so we
	don't drag half of libc in.

2002-07-22  James Antill  <james@and.org>

	* src/assert_loop.c (vstr__assert_loop): Only compile function is
	NDEBUG isn't set.

	* include/main.h (FIX_NAMESPACE_SYMBOL): Make the autoconf functions
	internal (linker script will now make them inaccessible).

2002-07-18  James Antill  <james@and.org>

	* include/vstr-internal.h (VSTR__I): Add internal attribute for symbols
	not called directly from outside the module.

	* include/vstr-inline.h (vstr_ref_del): Made inline.
	(vstr_ref_add): Made inline.

git-archimport-id: james@and.org--2004-code/vstr--main--1--patch-17

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -999,6 +999,9 @@ Optional Features:
   --enable-ansi           turn on ansi stuff (assumes gcc/gdb) default=no
   --enable-noposix-host   turn off all the POSIX extentions default=no
   --enable-linker-script  turn on linker version script default=no
+  --enable-tst-noinline   turn off use of inline default=no
+--enable-tst-noattr-visibility   turn off use of attribute visibility default=no
+--enable-tst-noattr-alias   turn off use of attribute alias default=no
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -1410,7 +1413,7 @@ echo "${ECHO_T}${T_MD}Initial phase:${T_ME}" >&6
 
 VSTR_MAJOR_VERSION=0
 VSTR_MINOR_VERSION=9
-VSTR_MICRO_VERSION=8
+VSTR_MICRO_VERSION=9
 VSTR_INTERFACE_AGE=0
 VSTR_BINARY_AGE=0
 VSTR_VERSION=$VSTR_MAJOR_VERSION.$VSTR_MINOR_VERSION.$VSTR_MICRO_VERSION
@@ -4660,7 +4663,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4663 "configure"' > conftest.$ac_ext
+  echo '#line 4666 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5196,7 +5199,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:5199: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:5202: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -6989,7 +6992,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6992 "configure"
+#line 6995 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7087,7 +7090,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7090 "configure"
+#line 7093 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8352,6 +8355,30 @@ _ACEOF
  ;;
 esac
 
+
+# Check whether --enable-tst-noinline or --disable-tst-noinline was given.
+if test "${enable_tst_noinline+set}" = set; then
+  enableval="$enable_tst_noinline"
+  local_cv_have_tst_noinline=true
+else
+  local_cv_have_tst_noinline=false
+fi;
+# Check whether --enable-tst-noattr-visibility or --disable-tst-noattr-visibility was given.
+if test "${enable_tst_noattr_visibility+set}" = set; then
+  enableval="$enable_tst_noattr_visibility"
+  local_cv_have_tst_noattr_visibility=true
+else
+  local_cv_have_tst_noattr_visibility=false
+fi;
+# Check whether --enable-tst-noattr-alias or --disable-tst-noattr-alias was given.
+if test "${enable_tst_noattr_alias+set}" = set; then
+  enableval="$enable_tst_noattr_alias"
+  local_cv_have_tst_noattr_alias=true
+else
+  local_cv_have_tst_noattr_alias=false
+fi;
+
+echo $local_cv_have_tst_noattr_alias $local_cv_have_tst_noattr_visibility $local_cv_have_tst_noinline
 
 
 # Check whether --with-fmt-float or --without-fmt-float was given.
@@ -12118,6 +12145,85 @@ fi
 done
 
 
+for ac_func in memmem
+do
+as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $ac_func" >&5
+echo $ECHO_N "checking for $ac_func... $ECHO_C" >&6
+if eval "test \"\${$as_ac_var+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char $ac_func (); below.  */
+#include <assert.h>
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char $ac_func ();
+char (*f) ();
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined (__stub_$ac_func) || defined (__stub___$ac_func)
+choke me
+#else
+f = $ac_func;
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "$as_ac_var=yes"
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+eval "$as_ac_var=no"
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_var'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_var'}'`" >&6
+if test `eval echo '${'$as_ac_var'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_func" | $as_tr_cpp` 1
+_ACEOF
+ cat >>confdefs.h <<\_ACEOF
+#define HAVE_MEMMEM 1
+_ACEOF
+
+fi
+done
+
+
 for ac_func in strspn
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
@@ -15572,6 +15678,9 @@ _ACEOF
 
 esac
 
+
+case x$local_cv_have_tst_noinline in
+ xfalse)
 echo "$as_me:$LINENO: checking if inline is a valid keyword" >&5
 echo $ECHO_N "checking if inline is a valid keyword... $ECHO_C" >&6
 if test "${local_cv_has_inline+set}" = set; then
@@ -15621,6 +15730,8 @@ fi
 
 echo "$as_me:$LINENO: result: $local_cv_has_inline" >&5
 echo "${ECHO_T}$local_cv_has_inline" >&6
+;;
+esac
 case x$local_cv_has_inline in
 xyes) cat >>confdefs.h <<\_ACEOF
 #define HAVE_INLINE 1
@@ -15628,6 +15739,13 @@ _ACEOF
  ;;
 esac
 
+# Beg testing attributes ... turn warnings into errors...
+XCFLAGS=$CFLAGS
+CFLAGS="-Werror $CFLAGS"
+
+
+case x$local_cv_have_tst_noattr_alias in
+ xfalse)
 echo "$as_me:$LINENO: checking if alias is a valid attribute" >&5
 echo $ECHO_N "checking if alias is a valid attribute... $ECHO_C" >&6
 if test "${local_cv_has_attrib_alias+set}" = set; then
@@ -15678,6 +15796,8 @@ fi
 
 echo "$as_me:$LINENO: result: $local_cv_has_attrib_alias" >&5
 echo "${ECHO_T}$local_cv_has_attrib_alias" >&6
+;;
+esac
 case x$local_cv_has_attrib_alias in
 xyes) cat >>confdefs.h <<\_ACEOF
 #define HAVE_ATTRIB_ALIAS 1
@@ -15685,6 +15805,65 @@ _ACEOF
  ;;
 esac
 
+echo "$as_me:$LINENO: checking if deprecated is a valid attribute" >&5
+echo $ECHO_N "checking if deprecated is a valid attribute... $ECHO_C" >&6
+if test "${local_cv_has_attrib_deprecated+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling" >&5
+echo "$as_me: error: cannot run test program while cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+#include <stdlib.h>
+#include <stdio.h>
+
+int abcd(void) { return (0); }
+extern int func(void) __attribute__((deprecated)) ;
+
+int main() {
+ return abcd();
+}
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  local_cv_has_attrib_deprecated=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+( exit $ac_status )
+local_cv_has_attrib_deprecated=no
+fi
+rm -f core core.* *.core conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+fi
+
+echo "$as_me:$LINENO: result: $local_cv_has_attrib_deprecated" >&5
+echo "${ECHO_T}$local_cv_has_attrib_deprecated" >&6
+case x$local_cv_has_attrib_deprecated in
+xyes) cat >>confdefs.h <<\_ACEOF
+#define HAVE_ATTRIB_DEPRECATED 1
+_ACEOF
+ ;;
+esac
+
+case x$local_cv_have_tst_noattr_visibility in
+ xfalse)
 echo "$as_me:$LINENO: checking if visibility is a valid attribute" >&5
 echo $ECHO_N "checking if visibility is a valid attribute... $ECHO_C" >&6
 if test "${local_cv_has_attrib_visibility+set}" = set; then
@@ -15735,12 +15914,73 @@ fi
 
 echo "$as_me:$LINENO: result: $local_cv_has_attrib_visibility" >&5
 echo "${ECHO_T}$local_cv_has_attrib_visibility" >&6
+;;
+esac
 case x$local_cv_has_attrib_visibility in
 xyes) cat >>confdefs.h <<\_ACEOF
 #define HAVE_ATTRIB_VISIBILITY 1
 _ACEOF
  ;;
 esac
+
+echo "$as_me:$LINENO: checking if nonnull is a valid attribute" >&5
+echo $ECHO_N "checking if nonnull is a valid attribute... $ECHO_C" >&6
+if test "${local_cv_has_attrib_nonnull+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling" >&5
+echo "$as_me: error: cannot run test program while cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+#include <stdlib.h>
+#include <stdio.h>
+
+int func(char *) __attribute__((nonnull)) ;
+int func(char *abcd) { return (!abcd); }
+
+int main() {
+ return func("abcd");
+}
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  local_cv_has_attrib_nonnull=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+( exit $ac_status )
+local_cv_has_attrib_nonnull=no
+fi
+rm -f core core.* *.core conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+fi
+
+echo "$as_me:$LINENO: result: $local_cv_has_attrib_nonnull" >&5
+echo "${ECHO_T}$local_cv_has_attrib_nonnull" >&6
+case x$local_cv_has_attrib_nonnull in
+xyes) cat >>confdefs.h <<\_ACEOF
+#define HAVE_ATTRIB_NONNULL 1
+_ACEOF
+ ;;
+esac
+CFLAGS=$XCFLAGS
+# End testing attributes ... turn CFLAGS back to normal
 
 echo "$as_me:$LINENO: checking if __typeof is a valid keyword" >&5
 echo $ECHO_N "checking if __typeof is a valid keyword... $ECHO_C" >&6
@@ -15808,7 +16048,7 @@ echo "${ECHO_T}${T_MD}Output Substitution:${T_ME}" >&6
 VSTR_LIBS="$LIBS"
 
 
-ac_config_files="$ac_config_files Makefile vstr.pc libtool_hack/Makefile src/Makefile include/Makefile Documentation/Makefile tst/Makefile tst/cache/Makefile tst/cmp/Makefile tst/conv/Makefile tst/fmt/Makefile tst/parse/Makefile src/vstr_version.c vstr.spec"
+ac_config_files="$ac_config_files Makefile vstr.pc libtool_hack/Makefile src/Makefile include/Makefile Documentation/Makefile tst/Makefile tst/add/Makefile tst/add_fmt/Makefile tst/cache/Makefile tst/cmp/Makefile tst/conv/Makefile tst/del/Makefile tst/export/Makefile tst/parse/Makefile src/vstr_version.c vstr.spec"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -16297,10 +16537,13 @@ do
   "include/Makefile" ) CONFIG_FILES="$CONFIG_FILES include/Makefile" ;;
   "Documentation/Makefile" ) CONFIG_FILES="$CONFIG_FILES Documentation/Makefile" ;;
   "tst/Makefile" ) CONFIG_FILES="$CONFIG_FILES tst/Makefile" ;;
+  "tst/add/Makefile" ) CONFIG_FILES="$CONFIG_FILES tst/add/Makefile" ;;
+  "tst/add_fmt/Makefile" ) CONFIG_FILES="$CONFIG_FILES tst/add_fmt/Makefile" ;;
   "tst/cache/Makefile" ) CONFIG_FILES="$CONFIG_FILES tst/cache/Makefile" ;;
   "tst/cmp/Makefile" ) CONFIG_FILES="$CONFIG_FILES tst/cmp/Makefile" ;;
   "tst/conv/Makefile" ) CONFIG_FILES="$CONFIG_FILES tst/conv/Makefile" ;;
-  "tst/fmt/Makefile" ) CONFIG_FILES="$CONFIG_FILES tst/fmt/Makefile" ;;
+  "tst/del/Makefile" ) CONFIG_FILES="$CONFIG_FILES tst/del/Makefile" ;;
+  "tst/export/Makefile" ) CONFIG_FILES="$CONFIG_FILES tst/export/Makefile" ;;
   "tst/parse/Makefile" ) CONFIG_FILES="$CONFIG_FILES tst/parse/Makefile" ;;
   "src/vstr_version.c" ) CONFIG_FILES="$CONFIG_FILES src/vstr_version.c" ;;
   "vstr.spec" ) CONFIG_FILES="$CONFIG_FILES vstr.spec" ;;
