Run autogen
git-archimport-id: james@and.org--2004-code/vstr--main--1--patch-65

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -463,7 +463,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CFLAGS CPPFLAGS LDFLAGS LT_RELEASE LT_CURRENT LT_REVISION LT_AGE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot CC ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CCAS CCASFLAGS build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL LIBTOOL_DEPS TRUE_PATH GZIP_PATH BZIP2_PATH SENDMAIL_PATH MAKE_PATH ETAGS_PATH SED_PATH PERL_PATH TAR_PATH CHMOD_PATH PKG_CONFIG TIMER_Q_AVAIL_TRUE TIMER_Q_AVAIL_FALSE TIMER_Q_CFLAGS TIMER_Q_LDLIBS SOCKET_POLL_AVAIL_TRUE SOCKET_POLL_AVAIL_FALSE SOCKET_POLL_CFLAGS SOCKET_POLL_LDLIBS OPENSSL_AVAIL_TRUE OPENSSL_AVAIL_FALSE OPENSSL_CFLAGS OPENSSL_LDLIBS GLIB20_AVAIL_TRUE GLIB20_AVAIL_FALSE GLIB20_CFLAGS GLIB20_LDLIBS NDEBUG_TRUE NDEBUG_FALSE WARNS HAVE_POSIX_HOST_TRUE HAVE_POSIX_HOST_FALSE HAVE_LINKER_VERSION_SCRIPT_TRUE HAVE_LINKER_VERSION_SCRIPT_FALSE USE_ASSERT_LOOP_TRUE USE_ASSERT_LOOP_FALSE USE_WRAP_MEMCPY_TRUE USE_WRAP_MEMCPY_FALSE USE_WRAP_MEMCMP_TRUE USE_WRAP_MEMCMP_FALSE USE_WRAP_MEMCHR_TRUE USE_WRAP_MEMCHR_FALSE USE_WRAP_MEMRCHR_TRUE USE_WRAP_MEMRCHR_FALSE USE_WRAP_MEMSET_TRUE USE_WRAP_MEMSET_FALSE USE_WRAP_MEMMOVE_TRUE USE_WRAP_MEMMOVE_FALSE LOCAL_EX_PROG_LIBS LOCAL_TST_PROG_LIBS FMT_DBL_host_TRUE FMT_DBL_host_FALSE FMT_DBL_none_TRUE FMT_DBL_none_FALSE FMT_DBL_glibc_TRUE FMT_DBL_glibc_FALSE GMP_AVAIL_TRUE GMP_AVAIL_FALSE GMP_CFLAGS GMP_LDLIBS ZLIB_AVAIL_TRUE ZLIB_AVAIL_FALSE ZLIB_CFLAGS ZLIB_LDLIBS BZ2_AVAIL_TRUE BZ2_AVAIL_FALSE BZ2_CFLAGS BZ2_LDLIBS ALLOCA HAVE_LINKER_MAIN_RELOCATE_TRUE HAVE_LINKER_MAIN_RELOCATE_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CFLAGS CPPFLAGS LDFLAGS LT_RELEASE LT_CURRENT LT_REVISION LT_AGE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot CC ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CCAS CCASFLAGS build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL LIBTOOL_DEPS TRUE_PATH GZIP_PATH BZIP2_PATH SENDMAIL_PATH MAKE_PATH ETAGS_PATH SED_PATH PERL_PATH TAR_PATH CHMOD_PATH PKG_CONFIG TIMER_Q_AVAIL_TRUE TIMER_Q_AVAIL_FALSE TIMER_Q_CFLAGS TIMER_Q_LDLIBS SOCKET_POLL_AVAIL_TRUE SOCKET_POLL_AVAIL_FALSE SOCKET_POLL_CFLAGS SOCKET_POLL_LDLIBS OPENSSL_AVAIL_TRUE OPENSSL_AVAIL_FALSE OPENSSL_CFLAGS OPENSSL_LDLIBS GLIB20_AVAIL_TRUE GLIB20_AVAIL_FALSE GLIB20_CFLAGS GLIB20_LDLIBS NDEBUG_TRUE NDEBUG_FALSE WARNS HAVE_POSIX_HOST_TRUE HAVE_POSIX_HOST_FALSE HAVE_LINKER_VERSION_SCRIPT_TRUE HAVE_LINKER_VERSION_SCRIPT_FALSE USE_ASSERT_LOOP_TRUE USE_ASSERT_LOOP_FALSE USE_WRAP_MEMCPY_TRUE USE_WRAP_MEMCPY_FALSE USE_WRAP_MEMCMP_TRUE USE_WRAP_MEMCMP_FALSE USE_WRAP_MEMCHR_TRUE USE_WRAP_MEMCHR_FALSE USE_WRAP_MEMRCHR_TRUE USE_WRAP_MEMRCHR_FALSE USE_WRAP_MEMSET_TRUE USE_WRAP_MEMSET_FALSE USE_WRAP_MEMMOVE_TRUE USE_WRAP_MEMMOVE_FALSE LOCAL_EX_PROG_LIBS LOCAL_TST_PROG_LIBS FMT_DBL_host_TRUE FMT_DBL_host_FALSE FMT_DBL_none_TRUE FMT_DBL_none_FALSE FMT_DBL_glibc_TRUE FMT_DBL_glibc_FALSE GMP_AVAIL_TRUE GMP_AVAIL_FALSE GMP_CFLAGS GMP_LDLIBS ZLIB_AVAIL_TRUE ZLIB_AVAIL_FALSE ZLIB_CFLAGS ZLIB_LDLIBS BZ2_AVAIL_TRUE BZ2_AVAIL_FALSE BZ2_CFLAGS BZ2_LDLIBS ALLOCA MALLINFO_AVAIL_TRUE MALLINFO_AVAIL_FALSE HAVE_LINKER_MAIN_RELOCATE_TRUE HAVE_LINKER_MAIN_RELOCATE_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1527,9 +1527,9 @@ echo "${ECHO_T}${T_MD}Initial phase:${T_ME}" >&6
 
 VSTR_MAJOR_VERSION=1
 VSTR_MINOR_VERSION=0
-VSTR_MICRO_VERSION=13
-VSTR_INTERFACE_AGE=0
-VSTR_BINARY_AGE=13
+VSTR_MICRO_VERSION=14
+VSTR_INTERFACE_AGE=1
+VSTR_BINARY_AGE=14
 VSTR_VERSION=$VSTR_MAJOR_VERSION.$VSTR_MINOR_VERSION.$VSTR_MICRO_VERSION
 
 # libtool versioning
@@ -28823,6 +28823,27 @@ xyes) cat >>confdefs.h <<\_ACEOF
 #define HAVE_MALLINFO 1
 _ACEOF
 
+
+
+if true; then
+  MALLINFO_AVAIL_TRUE=
+  MALLINFO_AVAIL_FALSE='#'
+else
+  MALLINFO_AVAIL_TRUE='#'
+  MALLINFO_AVAIL_FALSE=
+fi
+
+      ;;
+xno)
+
+if false; then
+  MALLINFO_AVAIL_TRUE=
+  MALLINFO_AVAIL_FALSE='#'
+else
+  MALLINFO_AVAIL_TRUE='#'
+  MALLINFO_AVAIL_FALSE=
+fi
+
 esac
 
 echo "$as_me:$LINENO: checking for termcap variables" >&5
@@ -30775,6 +30796,20 @@ echo "$as_me: error: conditional \"BZ2_AVAIL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${MALLINFO_AVAIL_TRUE}" && test -z "${MALLINFO_AVAIL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"MALLINFO_AVAIL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"MALLINFO_AVAIL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${MALLINFO_AVAIL_TRUE}" && test -z "${MALLINFO_AVAIL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"MALLINFO_AVAIL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"MALLINFO_AVAIL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${HAVE_LINKER_MAIN_RELOCATE_TRUE}" && test -z "${HAVE_LINKER_MAIN_RELOCATE_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_LINKER_MAIN_RELOCATE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -31463,6 +31498,8 @@ s,@BZ2_AVAIL_FALSE@,$BZ2_AVAIL_FALSE,;t t
 s,@BZ2_CFLAGS@,$BZ2_CFLAGS,;t t
 s,@BZ2_LDLIBS@,$BZ2_LDLIBS,;t t
 s,@ALLOCA@,$ALLOCA,;t t
+s,@MALLINFO_AVAIL_TRUE@,$MALLINFO_AVAIL_TRUE,;t t
+s,@MALLINFO_AVAIL_FALSE@,$MALLINFO_AVAIL_FALSE,;t t
 s,@HAVE_LINKER_MAIN_RELOCATE_TRUE@,$HAVE_LINKER_MAIN_RELOCATE_TRUE,;t t
 s,@HAVE_LINKER_MAIN_RELOCATE_FALSE@,$HAVE_LINKER_MAIN_RELOCATE_FALSE,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
