Fixes, example cleanup ... daemon controler
       * src/vstr_sc_posix.c (vstr_sc_write_fd): Fixed bug when UIO_MAXIOV is
       too big.
       (vstr_sc_read_len_file): Changed code to block until error or all data
       is read, makes function much more useful.
       (vstr_sc_write_file): Changed code to block until error or all data
       is written, makes function much more useful.
       (vstr_sc_read_iov_file): Changed code to block until error or all data
       is read, makes function much more useful.

.	HTTP/1.1 example bug fixes.
.	Added simple testing for cmd line examples.
.	Added controller for daemons.
.	Added local socket bindings.
.	Tided up example code, esp. event handling.

git-archimport-id: james@and.org--2004-code/vstr--main--1--patch-72

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -463,7 +463,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CFLAGS CPPFLAGS LDFLAGS LT_RELEASE LT_CURRENT LT_REVISION LT_AGE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot CC ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CCAS CCASFLAGS build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL LIBTOOL_DEPS TRUE_PATH GZIP_PATH BZIP2_PATH SENDMAIL_PATH MAKE_PATH ETAGS_PATH SED_PATH PERL_PATH TAR_PATH CHMOD_PATH PKG_CONFIG TIMER_Q_AVAIL_TRUE TIMER_Q_AVAIL_FALSE TIMER_Q_CFLAGS TIMER_Q_LDLIBS SOCKET_POLL_AVAIL_TRUE SOCKET_POLL_AVAIL_FALSE SOCKET_POLL_CFLAGS SOCKET_POLL_LDLIBS OPENSSL_AVAIL_TRUE OPENSSL_AVAIL_FALSE OPENSSL_CFLAGS OPENSSL_LDLIBS GLIB20_AVAIL_TRUE GLIB20_AVAIL_FALSE GLIB20_CFLAGS GLIB20_LDLIBS NDEBUG_TRUE NDEBUG_FALSE WARNS HAVE_POSIX_HOST_TRUE HAVE_POSIX_HOST_FALSE HAVE_LINKER_VERSION_SCRIPT_TRUE HAVE_LINKER_VERSION_SCRIPT_FALSE USE_ASSERT_LOOP_TRUE USE_ASSERT_LOOP_FALSE USE_WRAP_MEMCPY_TRUE USE_WRAP_MEMCPY_FALSE USE_WRAP_MEMCMP_TRUE USE_WRAP_MEMCMP_FALSE USE_WRAP_MEMCHR_TRUE USE_WRAP_MEMCHR_FALSE USE_WRAP_MEMRCHR_TRUE USE_WRAP_MEMRCHR_FALSE USE_WRAP_MEMSET_TRUE USE_WRAP_MEMSET_FALSE USE_WRAP_MEMMOVE_TRUE USE_WRAP_MEMMOVE_FALSE LOCAL_EX_PROG_LIBS LOCAL_TST_PROG_LIBS FMT_DBL_host_TRUE FMT_DBL_host_FALSE FMT_DBL_none_TRUE FMT_DBL_none_FALSE FMT_DBL_glibc_TRUE FMT_DBL_glibc_FALSE GMP_AVAIL_TRUE GMP_AVAIL_FALSE GMP_CFLAGS GMP_LDLIBS ZLIB_AVAIL_TRUE ZLIB_AVAIL_FALSE ZLIB_CFLAGS ZLIB_LDLIBS BZ2_AVAIL_TRUE BZ2_AVAIL_FALSE BZ2_CFLAGS BZ2_LDLIBS ALLOCA MALLINFO_AVAIL_TRUE MALLINFO_AVAIL_FALSE HAVE_LINKER_MAIN_RELOCATE_TRUE HAVE_LINKER_MAIN_RELOCATE_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CFLAGS CPPFLAGS LDFLAGS LT_RELEASE LT_CURRENT LT_REVISION LT_AGE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot CC ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CCAS CCASFLAGS build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL LIBTOOL_DEPS TRUE_PATH GZIP_PATH BZIP2_PATH SENDMAIL_PATH MAKE_PATH ETAGS_PATH SED_PATH PERL_PATH PERL_USR_BIN_AVAIL_TRUE PERL_USR_BIN_AVAIL_FALSE TAR_PATH CHMOD_PATH PKG_CONFIG TIMER_Q_AVAIL_TRUE TIMER_Q_AVAIL_FALSE TIMER_Q_CFLAGS TIMER_Q_LDLIBS SOCKET_POLL_AVAIL_TRUE SOCKET_POLL_AVAIL_FALSE SOCKET_POLL_CFLAGS SOCKET_POLL_LDLIBS OPENSSL_AVAIL_TRUE OPENSSL_AVAIL_FALSE OPENSSL_CFLAGS OPENSSL_LDLIBS GLIB20_AVAIL_TRUE GLIB20_AVAIL_FALSE GLIB20_CFLAGS GLIB20_LDLIBS NDEBUG_TRUE NDEBUG_FALSE WARNS HAVE_POSIX_HOST_TRUE HAVE_POSIX_HOST_FALSE HAVE_LINKER_VERSION_SCRIPT_TRUE HAVE_LINKER_VERSION_SCRIPT_FALSE USE_ASSERT_LOOP_TRUE USE_ASSERT_LOOP_FALSE USE_WRAP_MEMCPY_TRUE USE_WRAP_MEMCPY_FALSE USE_WRAP_MEMCMP_TRUE USE_WRAP_MEMCMP_FALSE USE_WRAP_MEMCHR_TRUE USE_WRAP_MEMCHR_FALSE USE_WRAP_MEMRCHR_TRUE USE_WRAP_MEMRCHR_FALSE USE_WRAP_MEMSET_TRUE USE_WRAP_MEMSET_FALSE USE_WRAP_MEMMOVE_TRUE USE_WRAP_MEMMOVE_FALSE LOCAL_EX_PROG_LIBS LOCAL_TST_PROG_LIBS FMT_DBL_host_TRUE FMT_DBL_host_FALSE FMT_DBL_none_TRUE FMT_DBL_none_FALSE FMT_DBL_glibc_TRUE FMT_DBL_glibc_FALSE GMP_AVAIL_TRUE GMP_AVAIL_FALSE GMP_CFLAGS GMP_LDLIBS ZLIB_AVAIL_TRUE ZLIB_AVAIL_FALSE ZLIB_CFLAGS ZLIB_LDLIBS BZ2_AVAIL_TRUE BZ2_AVAIL_FALSE BZ2_CFLAGS BZ2_LDLIBS ALLOCA MALLINFO_AVAIL_TRUE MALLINFO_AVAIL_FALSE HAVE_LINKER_MAIN_RELOCATE_TRUE HAVE_LINKER_MAIN_RELOCATE_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -19694,6 +19694,30 @@ echo "${ECHO_T}no" >&6
 fi
 
 
+if test "x$PERL_CONFIG" = "x/usr/bin/perl" ; then
+
+
+if false; then
+  PERL_USR_BIN_AVAIL_TRUE=
+  PERL_USR_BIN_AVAIL_FALSE='#'
+else
+  PERL_USR_BIN_AVAIL_TRUE='#'
+  PERL_USR_BIN_AVAIL_FALSE=
+fi
+
+else
+
+
+if true; then
+  PERL_USR_BIN_AVAIL_TRUE=
+  PERL_USR_BIN_AVAIL_FALSE='#'
+else
+  PERL_USR_BIN_AVAIL_TRUE='#'
+  PERL_USR_BIN_AVAIL_FALSE=
+fi
+
+fi
+
 # Extract the first word of "tar", so it can be a program name with args.
 set dummy tar; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -30551,6 +30575,20 @@ echo "$as_me: error: conditional \"am__fastdepCXX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${PERL_USR_BIN_AVAIL_TRUE}" && test -z "${PERL_USR_BIN_AVAIL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"PERL_USR_BIN_AVAIL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"PERL_USR_BIN_AVAIL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${PERL_USR_BIN_AVAIL_TRUE}" && test -z "${PERL_USR_BIN_AVAIL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"PERL_USR_BIN_AVAIL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"PERL_USR_BIN_AVAIL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${TIMER_Q_AVAIL_TRUE}" && test -z "${TIMER_Q_AVAIL_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"TIMER_Q_AVAIL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -31437,6 +31475,8 @@ s,@MAKE_PATH@,$MAKE_PATH,;t t
 s,@ETAGS_PATH@,$ETAGS_PATH,;t t
 s,@SED_PATH@,$SED_PATH,;t t
 s,@PERL_PATH@,$PERL_PATH,;t t
+s,@PERL_USR_BIN_AVAIL_TRUE@,$PERL_USR_BIN_AVAIL_TRUE,;t t
+s,@PERL_USR_BIN_AVAIL_FALSE@,$PERL_USR_BIN_AVAIL_FALSE,;t t
 s,@TAR_PATH@,$TAR_PATH,;t t
 s,@CHMOD_PATH@,$CHMOD_PATH,;t t
 s,@PKG_CONFIG@,$PKG_CONFIG,;t t
