Current changes for pre 1.0.13
2004-05-04  James Antill  <james@and.org>
 
        * src/vstr_add_fmt.c (vstr__add_fmt_number): Added uintptr_t as the
        convertion for %p.
 
2004-04-07  James Antill  <james@and.org>
 
        * src/vstr_parse.c (vstr_parse_num): Added function.
 
2004-04-05  James Antill  <james@and.org>
 
        * include/vstr-inline.h (vstr_iter_fwd_chr): Added function.
        (vstr_iter_pos): Added function.
        (vstr_iter_len): Added function.
        (vstr_iter_num): Added function.
 
        * src/vstr_split.c (vstr__split_hdl_null_mid): Fix null mid splitting
        return value on malloc error cases.
        (vstr__split_hdl_null_beg): Fix null beg splitting return value on
        malloc error cases.
 
2004-04-01  James Antill  <james@and.org>
 
        * src/vstr_sc_posix.c (vstr_sc_write_file): Fix return when close fails.        (vstr_sc_read_len_file): Fix return when close fails.
        (vstr_sc_read_iov_file): Fix return when close fails.
        (vstr_sc_mmap_file): Fix return when close fails.
        (vstr_sc_read_len_file): Fix uninit err variable.
 
2004-03-19  James Antill  <james@and.org>
 
        * include/vstr-inline.h (vstr_srch_cstr_buf_fwd): Added const to Vstr string
        (vstr_srch_cstr_buf_rev): Added const to Vstr string
        (vstr_srch_cstr_chrs_fwd): Added const to Vstr string
        (vstr_srch_cstr_chrs_rev): Added const to Vstr string
        (vstr_csrch_cstr_chrs_fwd): Added const to Vstr string
        (vstr_csrch_cstr_chrs_rev): Added const to Vstr string
        (vstr_srch_case_cstr_buf_fwd): Added const to Vstr string
        (vstr_srch_case_cstr_buf_rev): Added const to Vstr string
        (vstr_spn_cstr_chrs_fwd): Added const to Vstr string
        (vstr_spn_cstr_chrs_rev): Added const to Vstr string
        (vstr_cspn_cstr_chrs_fwd): Added const to Vstr string
        (vstr_cspn_cstr_chrs_rev): Added const to Vstr string
        (vstr_split_cstr_buf): Added const to Vstr string
        (vstr_split_cstr_chrs): Added const to Vstr string
 
2004-03-17  James Antill  <james@and.org>
 
        * src/vstr_add_fmt.c (vstr__add_fmt_wide_cstr): Fixed crash on win32
        (and other platforms wcsnrtombs doesn't act weird when first arg is
        NULL).
 
2004-03-10  James Antill  <james@and.org>
 
        * src/vstr_sc.c (vstr_sc_fmt_add_bkmg_Byte_uintmax): Added function.
        (vstr_sc_fmt_add_bkmg_Bytes_uintmax): Added function.
        (vstr_sc_fmt_add_bkmg_bit_uintmax): Added function.
        (vstr_sc_fmt_add_bkmg_bits_uintmax): Added function.
 
        * include/vstr-extern.h (VSTR_SC_FMT_ADD): Added macro function.
 
2004-02-18  James Antill  <james@and.org>
 
        * src/vstr_sc.c (vstr_sc_fmt_cb_beg): Fix bug where base was always
        taken as 16 for grouping lookups.
 
2004-02-08  James Antill  <james@and.org>
 
        * include/vstr-extern.h: Add ability to work out that off64_t isn't
        going to work at compile time, and skip those functions.
 
        * include/vstr-arch.h: Move include processing into a seperate file.
 
2004-01-27  James Antill  <james@and.org>
 
        * include/vstr.exported_symbols: Removed vstr_version_func from
        exported list of symbols ... running the library should work again.
        Removed vstr_extern_inline_make_cache_pos due to not being called
        from any internal code anymore.
 

git-archimport-id: james@and.org--2004-code/vstr--main--1--patch-43

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1525,9 +1525,9 @@ echo "${ECHO_T}${T_MD}Initial phase:${T_ME}" >&6
 
 VSTR_MAJOR_VERSION=1
 VSTR_MINOR_VERSION=0
-VSTR_MICRO_VERSION=12
+VSTR_MICRO_VERSION=13
 VSTR_INTERFACE_AGE=0
-VSTR_BINARY_AGE=12
+VSTR_BINARY_AGE=13
 VSTR_VERSION=$VSTR_MAJOR_VERSION.$VSTR_MINOR_VERSION.$VSTR_MICRO_VERSION
 
 # libtool versioning
@@ -3845,7 +3845,7 @@ fi
 
 
 # This could be better...
-CCAS=gcc
+CCAS=$CC
 
 CCASFLAGS="\$(DEFAULT_INCLUDES) \$(INCLUDES)"
 
@@ -19981,8 +19981,6 @@ fi
 
 fi;
 
-
-
 # Check whether --enable-wrap-memcpy or --disable-wrap-memcpy was given.
 if test "${enable_wrap_memcpy+set}" = set; then
   enableval="$enable_wrap_memcpy"
@@ -22325,10 +22323,12 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_type_off64_t" >&5
 echo "${ECHO_T}$ac_cv_type_off64_t" >&6
 if test $ac_cv_type_off64_t = yes; then
-  :
-else
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_OFF64_T 1
+_ACEOF
 
-cat >>confdefs.h <<_ACEOF
+else
+  cat >>confdefs.h <<_ACEOF
 #define off64_t off_t
 _ACEOF
 
@@ -22639,6 +22639,63 @@ else
 
 cat >>confdefs.h <<_ACEOF
 #define uintmax_t unsigned long
+_ACEOF
+
+fi
+
+echo "$as_me:$LINENO: checking for uintptr_t" >&5
+echo $ECHO_N "checking for uintptr_t... $ECHO_C" >&6
+if test "${ac_cv_type_uintptr_t+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+int
+main ()
+{
+if ((uintptr_t *) 0)
+  return 0;
+if (sizeof (uintptr_t))
+  return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_type_uintptr_t=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_type_uintptr_t=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_type_uintptr_t" >&5
+echo "${ECHO_T}$ac_cv_type_uintptr_t" >&6
+if test $ac_cv_type_uintptr_t = yes; then
+  :
+else
+
+cat >>confdefs.h <<_ACEOF
+#define uintptr_t unsigned long
 _ACEOF
 
 fi
