import 0.9.17
2002-10-03  James Antill  <james@and.org>

	* NEWS: Released 0.9.17

2002-10-02  James Antill  <james@and.org>

	* src/vstr_cache.c (vstr_nx_cache_set): Changed API.
	(vstr_nx_cache_add): Changed API.
	(vstr_nx_cache_cb_sub): Changed API.

	* include/vstr-inline.h (vstr_cache_get): Changed API.

2002-10-01  James Antill  <james@and.org>

	* include/vstr-switch.h (VSTR__COMPILE_ATTR_PURE): Added attribute to
	some functions.
	(VSTR__COMPILE_ATTR_MALLOC): Added attribute to	some functions.

	* src/vstr_cstr.c (vstr_export_cstr_malloc): Added function.

2002-09-30  James Antill  <james@and.org>

	* tst/tst-main.c: Changes to allow vstr to be built in a sub directory.

2002-09-28  James Antill  <james@and.org>

	* examples/ex_mon_cp.c (main): Fix bkmg functions to be the final API.

git-archimport-id: james@and.org--2004-code/vstr--main--1--patch-25

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1388,9 +1388,7 @@ ac_config_headers="$ac_config_headers include/autoconf.h"
 
 # Scary shtool stuff... borowed from pth-1.0
 if test ".`echo dummy $@ | grep help`" = .; then
-    SHTOOL="\$(TOP)/shtool"
-
-    ac_shtool="./shtool"
+    ac_shtool="$srcdir/shtool"
     T_MD="`$ac_shtool echo -n -e %B 2>/dev/null`"
     T_ME="`$ac_shtool echo -n -e %b 2>/dev/null`"
     echo "Configuring ${T_MD}vstr${T_ME}, (Library)${T_ME}"
@@ -1416,7 +1414,7 @@ echo "${ECHO_T}${T_MD}Initial phase:${T_ME}" >&6
 
 VSTR_MAJOR_VERSION=0
 VSTR_MINOR_VERSION=9
-VSTR_MICRO_VERSION=16
+VSTR_MICRO_VERSION=17
 VSTR_INTERFACE_AGE=0
 VSTR_BINARY_AGE=0
 VSTR_VERSION=$VSTR_MAJOR_VERSION.$VSTR_MINOR_VERSION.$VSTR_MICRO_VERSION
@@ -3456,10 +3454,11 @@ CCDEPMODE=depmode=$am_cv_CC_dependencies_compiler_type
 
 
 
-# No idea if this is right...
+# This could be better...
 CCAS=gcc
 
-CCASFLAGS=
+CCASFLAGS="\$(DEFAULT_INCLUDES) \$(INCLUDES)"
+
 
 
 echo "$as_me:$LINENO: result: " >&5
@@ -4975,7 +4974,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4978 "configure"' > conftest.$ac_ext
+  echo '#line 4977 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5511,7 +5510,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:5514: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:5513: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -7304,7 +7303,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7307 "configure"
+#line 7306 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7402,7 +7401,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7405 "configure"
+#line 7404 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -16584,6 +16583,178 @@ _ACEOF
  ;;
 esac
 
+echo "$as_me:$LINENO: checking if malloc is a valid attribute" >&5
+echo $ECHO_N "checking if malloc is a valid attribute... $ECHO_C" >&6
+if test "${local_cv_has_attrib_malloc+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling" >&5
+echo "$as_me: error: cannot run test program while cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+#include <stdlib.h>
+#include <stdio.h>
+
+int abcd(void *p) { return (!p); }
+void *func(void) __attribute__((malloc)) ;
+void *func(void) { return (malloc(4)); }
+
+int main() {
+ return abcd(func());
+}
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  local_cv_has_attrib_malloc=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+( exit $ac_status )
+local_cv_has_attrib_malloc=no
+fi
+rm -f core core.* *.core conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+fi
+
+echo "$as_me:$LINENO: result: $local_cv_has_attrib_malloc" >&5
+echo "${ECHO_T}$local_cv_has_attrib_malloc" >&6
+case x$local_cv_has_attrib_malloc in
+xyes) cat >>confdefs.h <<\_ACEOF
+#define HAVE_ATTRIB_MALLOC 1
+_ACEOF
+ ;;
+esac
+
+echo "$as_me:$LINENO: checking if nonnull is a valid attribute" >&5
+echo $ECHO_N "checking if nonnull is a valid attribute... $ECHO_C" >&6
+if test "${local_cv_has_attrib_nonnull+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling" >&5
+echo "$as_me: error: cannot run test program while cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+#include <stdlib.h>
+#include <stdio.h>
+
+int func(char *) __attribute__((nonnull)) ;
+int func(char *abcd) { return (!abcd); }
+
+int main() {
+ return func("abcd");
+}
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  local_cv_has_attrib_nonnull=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+( exit $ac_status )
+local_cv_has_attrib_nonnull=no
+fi
+rm -f core core.* *.core conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+fi
+
+echo "$as_me:$LINENO: result: $local_cv_has_attrib_nonnull" >&5
+echo "${ECHO_T}$local_cv_has_attrib_nonnull" >&6
+case x$local_cv_has_attrib_nonnull in
+xyes) cat >>confdefs.h <<\_ACEOF
+#define HAVE_ATTRIB_NONNULL 1
+_ACEOF
+ ;;
+esac
+
+echo "$as_me:$LINENO: checking if pure is a valid attribute" >&5
+echo $ECHO_N "checking if pure is a valid attribute... $ECHO_C" >&6
+if test "${local_cv_has_attrib_pure+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling" >&5
+echo "$as_me: error: cannot run test program while cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+#include <stdlib.h>
+#include <stdio.h>
+
+int abcd(int n)  __attribute__((pure)) ;
+int abcd(int n) { return (!n); }
+
+int main() {
+ return abcd(2);
+}
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  local_cv_has_attrib_pure=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+( exit $ac_status )
+local_cv_has_attrib_pure=no
+fi
+rm -f core core.* *.core conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+fi
+
+echo "$as_me:$LINENO: result: $local_cv_has_attrib_pure" >&5
+echo "${ECHO_T}$local_cv_has_attrib_pure" >&6
+case x$local_cv_has_attrib_pure in
+xyes) cat >>confdefs.h <<\_ACEOF
+#define HAVE_ATTRIB_PURE 1
+_ACEOF
+ ;;
+esac
+
 case x$local_cv_have_tst_noattr_visibility in
  xfalse)
 echo "$as_me:$LINENO: checking if visibility is a valid attribute" >&5
@@ -16645,62 +16816,8 @@ _ACEOF
  ;;
 esac
 
-echo "$as_me:$LINENO: checking if nonnull is a valid attribute" >&5
-echo $ECHO_N "checking if nonnull is a valid attribute... $ECHO_C" >&6
-if test "${local_cv_has_attrib_nonnull+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
 
-if test "$cross_compiling" = yes; then
-  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling" >&5
-echo "$as_me: error: cannot run test program while cross compiling" >&2;}
-   { (exit 1); exit 1; }; }
-else
-  cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
 
-#include <stdlib.h>
-#include <stdio.h>
-
-int func(char *) __attribute__((nonnull)) ;
-int func(char *abcd) { return (!abcd); }
-
-int main() {
- return func("abcd");
-}
-_ACEOF
-rm -f conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  local_cv_has_attrib_nonnull=yes
-else
-  echo "$as_me: program exited with status $ac_status" >&5
-echo "$as_me: failed program was:" >&5
-cat conftest.$ac_ext >&5
-( exit $ac_status )
-local_cv_has_attrib_nonnull=no
-fi
-rm -f core core.* *.core conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
-fi
-fi
-
-echo "$as_me:$LINENO: result: $local_cv_has_attrib_nonnull" >&5
-echo "${ECHO_T}$local_cv_has_attrib_nonnull" >&6
-case x$local_cv_has_attrib_nonnull in
-xyes) cat >>confdefs.h <<\_ACEOF
-#define HAVE_ATTRIB_NONNULL 1
-_ACEOF
- ;;
-esac
 CFLAGS=$XCFLAGS
 # End testing attributes ... turn CFLAGS back to normal
 
@@ -17453,7 +17570,6 @@ s,@ECHO_C@,$ECHO_C,;t t
 s,@ECHO_N@,$ECHO_N,;t t
 s,@ECHO_T@,$ECHO_T,;t t
 s,@LIBS@,$LIBS,;t t
-s,@SHTOOL@,$SHTOOL,;t t
 s,@CFLAGS@,$CFLAGS,;t t
 s,@CPPFLAGS@,$CPPFLAGS,;t t
 s,@LDFLAGS@,$LDFLAGS,;t t
