import 1.0.8
2003-09-22  James Antill  <james@and.org>

	* NEWS: Release-1.0.8

2003-09-20  James Antill  <james@and.org>

	* src/vstr_sc.c (vstr__sc_fmt_num_ipv6): Fix couple of bugs for length
	ipv6 output with IPV4 at the end.

2003-09-18  James Antill  <james@and.org>

	* include/vstr-switch.h (VSTR__COMPILE_ATTR_WARN_UNUSED_RET): Add
	warn_unused_return gcc compiler attribute.

	* include/vstr-extern.h (vstr_dup_rep_chr): Remove nonnull attribute.

	* src/vstr_cntl.c (vstr_cntl_opt): Fix fallthrough error when compiling
	in debug mode.

	* src/vstr_ref.c (vstr_ref_make_memdup): Add test for malloc failure.
	(vstr_ref_make_memdup): Change pointer to const, this is ABI compatible.
	(vstr_ref_make_ptr): Change pointer to const, this is ABI compatible.

2003-09-12  James Antill  <james@and.org>

	* include/vstr-inline.h (vstr_ref_make_strdup): Added function.

2003-09-02  James Antill  <james@and.org>

	* src/vstr_parse.c (vstr_parse_ipv4): Minor cidr wasn't written if
	ip was entire size of section.

2003-08-23  James Antill  <james@and.org>

	* Documentation/security_problems.txt: Added more
	classifications

git-archimport-id: james@and.org--2004-code/vstr--main--1--patch-38

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1423,9 +1423,9 @@ echo "${ECHO_T}${T_MD}Initial phase:${T_ME}" >&6
 
 VSTR_MAJOR_VERSION=1
 VSTR_MINOR_VERSION=0
-VSTR_MICRO_VERSION=7
-VSTR_INTERFACE_AGE=7
-VSTR_BINARY_AGE=7
+VSTR_MICRO_VERSION=8
+VSTR_INTERFACE_AGE=8
+VSTR_BINARY_AGE=8
 VSTR_VERSION=$VSTR_MAJOR_VERSION.$VSTR_MINOR_VERSION.$VSTR_MICRO_VERSION
 
 # libtool versioning
@@ -17418,6 +17418,62 @@ _ACEOF
  ;;
 esac
 
+echo "$as_me:$LINENO: checking if warn_unused_result is a valid attribute" >&5
+echo $ECHO_N "checking if warn_unused_result is a valid attribute... $ECHO_C" >&6
+if test "${local_cv_has_attrib_warn_unused_ret+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling" >&5
+echo "$as_me: error: cannot run test program while cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+#include <stdlib.h>
+#include <stdio.h>
+
+int func(char *) __attribute__((warn_unused_result)) ;
+int func(char *abcd) { return (!abcd); }
+
+int main() {
+ return func("abcd");
+}
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  local_cv_has_attrib_warn_unused_ret=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+( exit $ac_status )
+local_cv_has_attrib_warn_unused_ret=no
+fi
+rm -f core core.* *.core conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+fi
+
+echo "$as_me:$LINENO: result: $local_cv_has_attrib_warn_unused_ret" >&5
+echo "${ECHO_T}$local_cv_has_attrib_warn_unused_ret" >&6
+case x$local_cv_has_attrib_warn_unused_ret in
+xyes) cat >>confdefs.h <<\_ACEOF
+#define HAVE_ATTRIB_WARN_UNUSED_RET 1
+_ACEOF
+ ;;
+esac
 
 
 CFLAGS=$XCFLAGS
